#!/bin/sh
dt="$(date "+%a--%d-%b-%Y--%H.%M.%S--%Z")"

for f in *.djvu; do
	noext="${f%".djvu"}"
	if ! [ -f "${noext}.pdf" ]; then
		ddjvu -format=pdf "$f" "${noext}.pdf" 2>> "djvu2pdf.errors.${dt}" || :
	fi
done
