#!/bin/sh
#
#    Usage: get_urandom [LENGTH=32] [CLASS='[:graph:]']
#        Print random string of given length and POSIX char class.
#        Requires /dev/urandom.
 
tr -dc "${2:-"[:graph:]"}" </dev/urandom | head -c "${1:-32}"; echo
