#!/bin/sh
#
#    Usage: upto LIMIT COMMAND
#        Run COMMAND until LIMIT seconds have passed, then exit.
#
test "$1" -gt 0 || {
	printf '%s\n' " Error: first argument must be a positive integer."
	exit 1
}

sh -ic '
	sleeptime=$1
	shift
	exec 3>&1 2>&3
	{ 
		eval "$@" >&3
		kill 0
	} |
	{
		sleep "${sleeptime}"
		kill 0
	}
' sh "$@"
